# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4d65cd17695e8d06599b046732ec86d2a3f3728bdbb5249c922b6d50a5dace34e370a034cd779fd566eeaa0f94dc2739f7548931fa52e1442130e7498d65c19

test:
  secret_key_base: 55bba0a7931735439a8c8b23401faaa7a4435da3066da5c1a740252da8e510b07f864fa8ff503784e0748504ed312162bf5bb667cb225c60918604e7e7a4cb83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
